### ISSUE TITLE
Filament Seal Toggle

### ISSUE THREAD

**Issue by aidan-gibson** [QIDITECH/QIDIStudio#20]
<img width="336" alt="image" src="https://github.com/user-attachments/assets/f3a535d3-ffcb-4363-99b3-4b1681e7daf3">

What does this "Seal" toggle do?

**Comment by QIDITECH** [comment]
In extreme weather such as summer or winter, sealing and unpacking printing will have a greater impact on the printing effect. In order to make it more convenient for users to switch printing parameters according to actual needs, we added this parameter.
At present, only the use of auxiliary cooling fans in the printing process of some materials is affected.
